### ISSUE TITLE
Error prevaling while running dashboard

### ISSUE THREAD

**Issue by sohailg** [shadabsk/Sign-Language-Detection-Using-Hand-Gestures#14]
ImportError: cannot import name 'imread' from 'scipy.ndimage'

**Comment by shadabsk** [comment]
Remove or downgrade the scipy

pip install scipy==1.1.0

**Comment by sohailg** [comment]
not resolved!

**Comment by shadabsk** [comment]
Remove the existing installation of scipy package and install the scipy version 1.1.0 using the following command

Pip install scipy==1.1.0

You can also install imageio package and then simply use it as

from imageio import imread

**Comment by zeusdomz** [comment]
still not opening
