### ISSUE TITLE
Dashboard not opening

### ISSUE THREAD

**Issue by 11041997** [shadabsk/Sign-Language-Detection-Using-Hand-Gestures#15]
please help me
when I double click on dashboard.py the cmd window comes and goes away. So I tried to run dashboard.py in visual studio code , i got error: 
cannot import name 'imread' from 'scipy.ndimage:
![IMG-20200705-WA0008](https://user-images.githubusercontent.com/67870681/86537076-15877b00-bf0a-11ea-9474-e253a711a19a.jpeg)

**Comment by shadabsk** [comment]
The scipy update has deprecated that method, the solution is changed that line to
Install imageio package, and use imread method

Installation command:
Pip install imageio 

Importing syntax:
From imageio import imread
