### ISSUE TITLE
pywrap tensorflow error

### ISSUE THREAD

**Issue by 11041997** [shadabsk/Sign-Language-Detection-Using-Hand-Gestures#16]
![IMG20200705222820](https://user-images.githubusercontent.com/67870681/86616066-ef79dd80-bfd2-11ea-8fa5-b228a1113d3a.jpg)

please help

**Comment by shadabsk** [comment]
Please verify if you have tensorflow and not the GPU version and check whether it's available in the environment variables

Step 1: pip uninstall tensorflow_gpu

Step 2: pip uninstall tensorflow (sometimes you don't need this)

Step 3: pip install tensorflow

Reference:
https://stackoverflow.com/questions/43903360/trying-to-install-tensorflow-on-windows-10-no-module-named-pywrap-tensorflow

**Comment by 11041997** [comment]
hi
please help me

still getting this error
