### ISSUE TITLE
error plz help

### ISSUE THREAD

**Issue by 10121998** [shadabsk/Sign-Language-Detection-Using-Hand-Gestures#17]
`
![IMG_20200707_000706 1](https://user-images.githubusercontent.com/67924619/86629222-b51b3b00-bfe8-11ea-96ac-26b1e296ea41.jpg)

**Comment by shadabsk** [comment]
The assertion error in opencv are related to the resolution or certain frames not being able to capture.. please do check the specifications of the camera interface whether it's matching as specified in the project report. 

One tweak you can do on the line wherever you are encountering such error, wrap up them with try and catch block and you will be good to go!

**Comment by 10121998** [comment]
thanks,it worked.

**Comment by shadabsk** [comment]
Glad to know!
