### ISSUE TITLE
ImportError: cannot import name 'imread' from 'scipy.ndimage'

### ISSUE THREAD

**Issue by Harish-sy** [shadabsk/Sign-Language-Detection-Using-Hand-Gestures#19]
Traceback (most recent call last):
  File "Dashboard.py", line 9, in <module>
    from scipy.ndimage import imread                            #will help in reading the images
ImportError: cannot import name 'imread' from 'scipy.ndimage'

**Comment by Rohitkumarded99** [comment]
Import correlate in the place of imread

**Comment by shadabsk** [comment]
The scipy update has deprecated that method, the solution is changed that line to
Install imageio package, and use imread method

Installation command:
Pip install imageio

Importing syntax:
From imageio import imread
